content:
  - name: Pages
    label: Website Pages
    type: collection
    path: src
    fields:
      - name: title
        label: Page Title
        type: string
      - name: body
        label: Content
        type: rich-text

  - name: uploads
    label: Images & Assets
    type: collection
    path: assets/images